ProTwo/AppTwo/urls.py
from django.conf.urls import url
from AppTwo import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^access_record/', views.access_record,  name='access_record'),
    url(r'^help/', views.help, name='help'),
    url(r'^users/', views.users, name='users'),
    url(r'^first_form/', views.form_name_view, name='first_form'),
]

ProTwo/ProTwo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from AppTwo import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^help/', views.help, name='help'), # this will be mapped with any page with extension help/
    url(r'apptwo/', include('AppTwo.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^sa/', include('AppTwo.urls')), #on the place of sa we can any word what we want to use in browser.
    url(r'^basicapp/', include('basic_app.urls')),
    
]

ProTwo/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),
    url(r'^base/$',views.base, name='base'),
    url(r'^register/$',views.register, name='register'),
    url(r'^user_login/$',views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/',views.special,name='special'),
]

ProTwo/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

ProTwo/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

ProTwo/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    my_cont = {'text':'template filter test', 'number':100}
    return render(request, 'basic_app/index.html', context=my_cont)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_template.html')
def base(request):
    return render(request, 'basic_app/base.html')

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)
    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))



def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

ProTwo/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base Form</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}"> AppTwo </a> </li>
          <li> <a class="navbar-brand" href="{% url 'basic_app:index' %}"> BRAND </a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a> </li>
          <li> <a class="navbar-link" href="{% url 'basic_app:base' %}">  Base  </a> </li>
          <li> <a class="navbar-link" href="{% url 'basic_app:register' %}">  Register  </a> </li>


          {% if user.is_authenticated %}
            <li><a href="{% url 'basic_app:logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}

        </ul>

      </div>

    </nav>

    <div class="container">
      {% block body_block%}
        <h2>This is base page</h2>
      {% endblock %}
    </div>

  </body>
</html>

ProTwo/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block%}
<div class="jumbotron">
  <h2>This is index page</h2>
  <h2> {{text|upper}} </h2>
  <h2>{{text|title}}</h2>
  <h2>{{number}}</h2>
  <h2>  {{number|add:'99'}} </h2>
  <h2> {{text|cut:'test'}}  </h2>
</div>

{% endblock %}

ProTwo/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'basic_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

ProTwo/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}

{% block body_block %}
  <h1>this is other page</h1>
{% endblock %}

ProTwo/templates/basic_app/registration.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h2>Register here</h2>
      <h3>Fill out the form</h3>
      <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

    {% endif %}
  </div>
{% endblock %}

ProTwo/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>RELATIVE URL TEMPLATE</h1>
    <!-- <a href="basic_app/other.html"> OTHER PAGE</a> -->
    <!--  Above will not work because this is not relative url representation
        When above link is clicked it will call following in page domain/basicapp/relative/basic_app/other.html
        current page is domain/basicapp/relative/ so on clicking the link basic_app/other.html will be added to it
    -->
    <a href="{% url 'basic_app:other' %}">OTHER PAGE</a>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a>
    <a href="{% url 'index' %}"> INDEX PAGE </a>
  </body>
</html>